import { DataRecord } from '../models/data-record';

export const MOCK_DATA: DataRecord[] = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    company: 'Northwind',
    role: 'Admin',
    status: 'Active',
    country: 'Italy',
    createdAt: '2025-12-15',
    score: 88,
  },
  {
    id: 2,
    name: 'Marco Rossi',
    email: 'marco.rossi@example.com',
    company: 'Contoso',
    role: 'Editor',
    status: 'Pending',
    country: 'Italy',
    createdAt: '2026-01-10',
    score: 72,
  },
  {
    id: 3,
    name: 'Sofia Martinez',
    email: 'sofia.martinez@example.com',
    company: 'Globex',
    role: 'Viewer',
    status: 'Active',
    country: 'Spain',
    createdAt: '2025-11-22',
    score: 91,
  },
  {
    id: 4,
    name: 'Liam Brown',
    email: 'liam.brown@example.com',
    company: 'Initech',
    role: 'Editor',
    status: 'Suspended',
    country: 'United Kingdom',
    createdAt: '2025-09-03',
    score: 64,
  },
  {
    id: 5,
    name: 'Giulia Bianchi',
    email: 'giulia.bianchi@example.com',
    company: 'Umbrella',
    role: 'Admin',
    status: 'Active',
    country: 'Italy',
    createdAt: '2026-02-05',
    score: 95,
  },
  {
    id: 6,
    name: 'Noah Wilson',
    email: 'noah.wilson@example.com',
    company: 'Soylent',
    role: 'Viewer',
    status: 'Pending',
    country: 'USA',
    createdAt: '2025-10-18',
    score: 59,
  },
  {
    id: 7,
    name: 'Emma Garcia',
    email: 'emma.garcia@example.com',
    company: 'Hooli',
    role: 'Editor',
    status: 'Active',
    country: 'France',
    createdAt: '2026-01-28',
    score: 83,
  },
  {
    id: 8,
    name: 'David Lee',
    email: 'david.lee@example.com',
    company: 'Vehement',
    role: 'Viewer',
    status: 'Suspended',
    country: 'Germany',
    createdAt: '2025-08-14',
    score: 67,
  }
];